export const UPDATE_CURRENT_CURRENCY = "UPDATE_CURRENT_CURRENCY";
export const UPDATE_TARGET_CURRENCY = "UPDATE_TARGET_CURRENCY";
export const UPDATE_RATE = "UPDATE_RATE";
export const UPDATE_AMOUNT = "UPDATE_AMOUNT";
export const UPDATE_SELL_OR_BUY = "UPDATE_SELL_OR_BUY";
export const UPDATE_IS_EXCEED = "UPDATE_IS_EXCEED";
export const UPDATE_CURRENCY_LIST = "UPDATE_CURRENCY_LIST";
